export const HostelData = [
  {
    id: 1,
    img: "https://cms.hostelworld.com/hwblog/wp-content/uploads/sites/2/2019/01/7-1.jpg",
    Hostelname: "Banglore Hostels",
    location: "Bangalore",
    interest: "Sports",
    currentuser: "John, David, Ram",
    price: "2500",
    rating: "4.5",
  },
  {
    id: 2,
    img: "https://q-xx.bstatic.com/xdata/images/hotel/840x460/232170506.jpg?k=289df3071803a2a7374b34c9fb956b6d8884ecf9c6d17ddf8c597bbc1cbdfaa3&o=",
    Hostelname: "Chennai Hostels",
    location: "Chennai",
    interest: "Sports",
    currentuser: "Venkat, Joseph",
    price: "1200",
    rating: "4.2",
  },
  {
    id: 3,
    img: "https://hostelgeeks.com/wp-content/uploads/2016/04/hostel-room-types-dorms-1200x630-cropped.jpg",
    Hostelname: "Hyderabad Hostels",
    location: "Hyderabad",
    interest: "Music",
    currentuser: "Krishna, Suman",
    price: "1800",
    rating: "4.7",
  },
  {
    id: 4,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8Lu4Y1r05jqiT5SMYdrRdGPmnMkfXkfSn1Il3VvFQKses4n-GNe8ImNDOEW3wlWITT8k&usqp=CAU",
    Hostelname: "Delhi Hostels",
    location: "Delhi",
    interest: "Art",
    currentuser: "Manu, Pavan, Sai",
    price: "3400",
    rating: "4.3",
  },
  {
    id: 5,
    img: "https://media-cdn.tripadvisor.com/media/photo-s/12/50/8b/bf/mad-monkey-hostel-boracay.jpg",
    Hostelname: "Mumbai Hostels",
    location: "Mumbai",
    interest: "Dance",
    currentuser: "Ganesh, Arjun",
    price: "3800",
    rating: "4.5",
  },
  {
    id: 6,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJNrzRIiOpH8V0nM-x08cTco3TEOQV4G6KNQ&usqp=CAU",
    Hostelname: "Kolkata Hostels",
    location: "Kolkata",
    interest: "Travel",
    currentuser: "Avinash, Chaitanya, Abhay",
    price: "2200",
    rating: "4.4",
  },
  {
    id: 7,
    img: "https://www.bowringandladycurzonmedicalcollege.org/wp-content/uploads/2020/11/3a.jpg",
    Hostelname: "Jaipur Hostels",
    location: "Jaipur",
    interest: "Fitness",
    currentuser: "Anirudh, Mahesh",
    price: "1900",
    rating: "3.9",
  },
  {
    id: 8,
    img: "https://qph.fs.quoracdn.net/main-qimg-47fff53340e963082827560fa060fcd0",
    Hostelname: "Lucknow Hostels",
    location: "Lucknow",
    interest: "Music",
    currentuser: "Salman, Nitish",
    price: "2300",
    rating: "4.1",
  },
  {
    id: 9,
    img: "https://5.imimg.com/data5/WX/JV/GLADMIN-31139027/ac-room-service-500x500.png",
    Hostelname: "Visakhapatnam Hostels",
    location: "Visakhapatnam",
    interest: "Photography",
    currentuser: "Kumar, Kiran, Manohar",
    price: "2800",
    rating: "4.6",
  },
  {
    id: 10,
    img: "https://i.pinimg.com/236x/ce/a9/4b/cea94bb9ce132303dfddea920452656d.jpg",
    Hostelname: "Srinagar Hostels",
    location: "Srinagar",
    interest: "Travel",
    currentuser: "Ali, Jimmy",
    price: "3100",
    rating: "4.1",
  },
];
